version: '1.0'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
    networks:
      backend:
        aliases:
          - "kafka"
  configserver:
    image: ing/config-server:0.0.1-SNAPSHOT
    container_name: config-server
    ports:
      - "8071:8071"
    networks:
      backend:
        aliases:
          - "config-server"
  eurekaserver:
    image: ing/eureka-server:0.0.1-SNAPSHOT
    container_name: eureka-server
    ports:
      - "8070:8070"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eureka-server"
  smartwatchapp:
    image: ing/app:0.0.1-SNAPSHOT
    container_name: app
    environment:
      PROFILE: "dev"
    depends_on:
      configserver:
        condition: service_started
      kafkaserver:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - backend

  smartwatchbackend:
    image: ing/backend:0.0.1-SNAPSHOT
    container_name: backend
    environment:
      PROFILE: "dev"
    depends_on:
      configserver:
        condition: service_started
      kafkaserver:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend:
    driver: bridge
